# Generated by Django 2.2.2 on 2019-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackgoUnivEnterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=100)),
                ('univ_enterance_type', models.CharField(max_length=100)),
                ('univ_enterance_name', models.CharField(max_length=100)),
                ('univ_url', models.URLField(verbose_name='University URL')),
            ],
        ),
    ]
